server:
  port: 8086
spring:
  rabbitmq:
    host: 192.168.230.132 #你的的虚拟机IP
    port: 5672 # 端口
    virtual-host: /hmall # 虚拟主机
    username: hmall # 用户名
    password: 123 # 密码
hm:
  db:
    database: hm-pay
  swagger:
    title: "黑马商城支付服务接口文档"
    package: com.hmall.pay.controller
