---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ASUS.
--- DateTime: 2024/9/25 18:46
---
--- 1.参数列表
--- 1.1优惠券id
local voucherId = ARGV[1]
--- 1.2用户id
local userId = ARGV[2]
--- 1.2订单id
local orderId = ARGV[3]

--- 2.数据
--- 2.1库存
local stockKey = 'seckill:stock:' .. voucherId
--- 2.2订单key
local orderKey = 'seckill:order:' .. voucherId

--- 3脚本业务
--- 3.1判断库存是否充足 get stockKey
if(tonumber(redis.call('get',stockKey))<=0) then
    ---3.2 库存不足，返回1
    return 2
end
--- 3.2判断用户是否下单 SISMEMBER orderKey userId
if(redis.call('sismember',orderKey,userId)==1) then
    --- 3.3存在，说明是重复下单，返回2
    return 2
end
--- 3.4 扣库存 incrby stockKey -1   自增-1 就是-1
redis.call('incrby',stockKey,-1)
--- 3.5 下单（保存用户） sadd orderKey userId
redis.call('sadd',orderKey,userId)

--- 修改Lua脚本，在认定有抢购资格后，直接向stream.orders添加消息
--- 3.6 发送消息到队列中，XADD stream.orders * k1 v1 k2 v2...
redis.call('xadd','stream.orders','*','userId',userId,'voucherId',voucherId,'id',orderId)
return 0